version: '3'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
